services:
  python-bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BOT_TOKEN: ${BOT_TOKEN}
        GUILD_IDS: ${GUILD_IDS}
        OPENAI_API_KEY: ${OPENAI_API_KEY}
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - GUILD_IDS=${GUILD_IDS}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    container_name: python-bot
    command: python src/bot.py
