name: Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin docker.io

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image and run tests
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.test
        load: true
        tags: discord-chatgpt-test:latest
        secrets: |
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}

    - name: Run Docker container to execute tests
      run: docker run discord-chatgpt-test
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
