name: Docker CI

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push release image
      uses: docker/build-push-action@v5
      with:
        push: true
        context: .
        file: ./Dockerfile
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/discord-chatgpt:latest
      env: 
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    - name: Build test image
      uses: docker/build-push-action@v5
      with:
        push: false
        context: .
        file: ./Dockerfile.test
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/discord-chatgpt-test:latest

    - name: Run Docker container to execute tests
      run: docker run discord-chatgpt-test
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}